# Site
title: Quantifying the Relationship of Nutritional Values in Recipes
bio: by Megan Yu (mey010@ucsd.edu)
description: Research project at UCSD for DSC80 exploring predictive relationships between macronutrients in recipes. Analysis performed with linear correlation modeling, EDA, and regression pipelines.
url: "https://github.com/megan-e3/nutrition-metric-modeling.git"

# Jekyll settings
permalink: /:title/
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - _site
  - vendor